server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: party-service
          uri: http://localhost:9091/
          predicates:
            - Path=/party/
        - id: leader-service
          uri: http://localhost:9092/
          predicates:
            - Path=/leader/
        - id: development-service
          uri: http://localhost:9093/
          predicates:
            - Path=/development/
management:
  endpoints:
    web:
      exposure:
        include: "*"
