server:
  port: 8080
spring:
  application:
    name: application-gateway
  cloud:
    gateway:
      routes:
        - id: party-service
          uri: ${PARTY_SERVICE:http://localhost:9091/ }
          predicates:
            - Path=/party/**
        - id: leader-service
          uri: ${LEADER_SERVICE:http://localhost:9092/ }
          predicates:
            - Path=/leader/**
        - id: development-service
          uri: ${DEV_SERVICE:http://localhost:9093/ }
          predicates:
            - Path=/development/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}